#### Project: MinneMap
##### Class: Stat 360
##### Date Due: 
##### Created By: 
##### Project Description: 

```{r}
# Setting up git in the Terminal:
#git config --global user.name 'Jane Doe'
#git config --global user.email 'jane@example.com'
#git config credential.helper 'cache 7200'
```

```{r}
# install.packages("fivethirtyeight")
# install.packages("tidyverse")
# install.packages("googleway")
# install.packages("leaflet")
# install.packages("geosphere")

library(fivethirtyeight)
library(tidyverse)
library(googleway)
library(leaflet)
library(geosphere)

## using a valid Google Maps API key
## this key was made using my personal google account: trevorptracy@gmail.com
key <- "AIzaSyDea9BHdMYeXvLUjJObACk2Ox8ofse2m68"

```


```{r}
## 2nd example of googleway with MN locations

## using a valid Google Maps API key

## Using the first and last coordinates as the origin/destination
origin <- c(44.952180, -93.182773)
destination <- c(44.886176, -93.247371)

## and the coordinates in between as waypoints
waypoints <- list(via = c(44.945816, -93.298559))#,
#                  via = c(17.51965, 78.37835),
#                  via = c(17.49359, 78.40079),
#                  via = c(17.49284, 78.40686))
## use 'stop' in place of 'via' for stopovers

## get the directions from Google Maps API
res <- google_directions(origin = origin,
                         destination = destination,
                         waypoints = waypoints,
                         key = key)  ## include simplify = F to return data as JSON

green_line <- google_directions(origin = "Union Depot Station, Minnesota",
                              destination = "Target Field Station, Minnesota",
                              key = key,
                              mode = 'transit')

blue_line <- google_directions(origin = "Target Field, Minnesota",
                              destination = "Mall of America, Minnesota",
                              key = key,
                              mode = 'transit')

#############################################################
## This section gets the distance and duration of the #######
## trip based on the 'res' result of 'google_directions()'
stored_frame <- data.frame(green_line$routes$legs)
stored_frame$distance
stored_frame$duration
## We may be able to use this to pick the best new transit
## system because the shortest travel time/distance will
## likely be the cheapest to produce for any given set of
## locations.
##
## Algorithmically, given a set of n locations, the
## number of potential solutions would be n!.
## This means 10 locations will involves calculating
## 3,628,800 routes and choosing the shortest. It is likely
## that is is too many calculations and we will have to be
## smarter with how to determine waypoint order.
##
## E.g. we could make the origin and destination be the
## coordinates that are the furthest from each other. From
## there, take either coordinate and find the next closest.
## etc, etc, etc.
#############################################################

df_polyline1 <- decode_pl(res$routes$overview_polyline$points)
df_polyline_greenline <- decode_pl(green_line$routes$overview_polyline$points)
df_polyline_blueline <- decode_pl(blue_line$routes$overview_polyline$points)
#df_polyline

library(leaflet)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = df_polyline1, lat = ~lat, lng = ~lon, color = "yellow") %>%
  addPolylines(data = df_polyline_greenline, lat = ~lat, lng = ~lon, color = "green") %>%
  addPolylines(data = df_polyline_blueline, lat = ~lat, lng = ~lon, color = "blue")
```

```{r}
# Documentation: https://rdrr.io/cran/googleway/man/google_directions.html
```

```{r}
##Pull location coordinates
rad<-10000
origin<-c(44.97566,-93.2696761)
max.page<-3
loca<-"Starbucks"
i<-1

McD<-NULL
McData<-NULL
McData2<- NULL
for (i in 1:max.page){
  if(i == 1){
      McD <- google_places(search_string = loca, location = origin, radius = rad, key = c("AIzaSyDea9BHdMYeXvLUjJObACk2Ox8ofse2m68"))
  }
  else{
      McD <- google_places(search_string = loca, location = origin, radius = rad, key = c("AIzaSyDea9BHdMYeXvLUjJObACk2Ox8ofse2m68"), page_token = token)
  }
  token<-McD$next_page_token
  McData2<-McD$results[2]$geometry$location
  McData<-bind_rows(McData,McData2)
  Sys.sleep(3)
}
```
```{r}
##Clean and plot coordinates
test<-McData
test[,2]<-test[,2]+90
##Adjust longitude set

filtered_points <- test %>% 
  filter(!distm(c(44.97566,-3.2696761), test[,], fun = distHaversine)>16100)

filtered_points %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng-90)
```

```{r}
##Create sub-clusters
sub_clust <- kmeans(filtered_points, centers = 8)

as.data.frame(sub_clust$centers) %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng -90)

##Create center of sub-cluster
cent_sub_clust <- kmeans(sub_clust$centers, centers = 2)

as.data.frame(cent_sub_clust$centers) %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng -90)
```


```{r}




```










