---
title: "MinnieMap"
author: "Peter Roessler-Caram"
date: "5/14/2019"
output: html_document
---

#### Project: MinneMap
##### Class: Stat 360
##### Date Due: 
##### Created By: 
##### Project Description: 

```{r}
# Setting up git in the Terminal:
#git config --global user.name 'Jane Doe'
#git config --global user.email 'jane@example.com'
#git config credential.helper 'cache 7200'
```

```{r}
#> install.packages("tidyverse")
#> install.packages("googleway")
#> install.packages("leaflet")

library(tidyverse)
library(googleway)
library(leaflet)
library(geosphere)

## using a valid Google Maps API key
## this key was made using my personal google account: trevorptracy@gmail.com
key <- "AIzaSyDea9BHdMYeXvLUjJObACk2Ox8ofse2m68"

```

```{r}
##Pull location coordinates
rad<-10000
origin<-c(44.97566,-93.2696761)
max.page<-3
loca<-"Starbucks"
##This will be the location to pull
i<-1

McD<-NULL
McData<-NULL
McData2<- NULL
for (i in 1:max.page){
  if(i == 1){
      McD <- google_places(search_string = loca, location = origin, radius = rad, key = key)
  }
  else{
      McD <- google_places(search_string = loca, location = origin, radius = rad, key = key, page_token = token)
  }
  token<-McD$next_page_token
  McData2<-McD$results[2]$geometry$location
  McData<-bind_rows(McData,McData2)
  Sys.sleep(3)
}
```
```{r}
##Clean and plot coordinates
test<-McData
test[,2]<-test[,2]+90
##Adjust longitude set

filtered_points <- test %>% 
  filter(!distm(c(44.97566,-3.2696761), test[,], fun = distHaversine)>16100)

filtered_points %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng-90)

filtered_points_90 <- cbind( lat = filtered_points[,1], lng = filtered_points[,2]-90)
```

```{r}
##Create sub-clusters
sub_clust <- kmeans(filtered_points_90, centers = 8)

as.data.frame(sub_clust$centers) %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng)

##Create center of sub-cluster
cent_sub_clust <- kmeans(sub_clust$centers, centers = 1)

as.data.frame(cent_sub_clust$centers) %>% 
  leaflet() %>%
    addTiles() %>%
    addMarkers(lat = ~lat, lng = ~lng)
```
```{r}
##Waypoint calculation for 1 path
##i<-1
df_polyline<-NULL
##for(i in 1:8){
  
  origin<- sub_clust$centers[1,]
  destination<- as.numeric(cent_sub_clust$centers)
##waypoints<-
  
  test.waypoints <- google_directions(origin = origin,
                          destination = destination,
                          ##waypoints = waypoints,
                          key = key)
  df_polyline <- decode_pl(test.waypoints$routes$overview_polyline$points)
  ##if(i == 1){
    ##full_way <- df_polyline
  ##}
  ##else{
    ##full_way <- cbind(full_way, df_polyline)
    ##}
##}
```
```{r}
df_polyline[] %>% 
  leaflet() %>%
    addTiles() %>%
    addPolylines(lat = ~lat, lng = ~lon, color = "purple")
```











